project:
    name: "droid/nfs-client"
    description: "Install and configure an NFS client and mount a share"

variables:
    module_nfs_client:
        share: ~
            # host: nfs.example.com
            # path: /share
        mount: ~
            # path: /share
            # mode: 0777
            # opts: rw

tasks:
    -
      name: "Install droid-managed /etc/hosts.deny configuration."
      command: "fs:copy"
      arguments:
          src: "!{{ mod_path }}/assets/etc/hosts.deny.template"
          dest: "/etc/hosts.deny"
    -
      name: "Install droid-managed /etc/hosts.allow configuration."
      command: "fs:copy"
      arguments:
          src: "!{{ mod_path }}/assets/etc/hosts.allow.template"
          dest: "/etc/hosts.allow"
    -
      name: "Install droid-managed /etc/modprobe.d/lockd.conf configuration."
      command: "fs:copy"
      arguments:
          src: "!{{ mod_path }}/assets/etc/modprobe.d/lockd.conf.template"
          dest: "/etc/modprobe.d/lockd.conf"
      trigger: "Reboot"
    -
      name: "Install nfs-common package"
      command: "apt-get:install"
      arguments:
          package: "nfs-common"
    -
      name: "Install droid-managed /etc/default/nfs-common configuration."
      command: "fs:copy"
      arguments:
          src: "!{{ mod_path }}/assets/etc/default/nfs-common.template"
          dest: "/etc/default/nfs-common"
    -
      name: "Make NFS share mount point"
      command: "fs:mkdir"
      arguments:
          directory: "{{{ module_nfs_client.mount.path }}}"
          mode: "{{{ module_nfs_client.mount.mode }}}"
    -
      name: "Configure the mounting of an NFS share"
      command: "fs:mount"
      arguments:
          filesystem: "{{{ module_nfs_client.share.host }}}:{{{ module_nfs_client.share.path }}}"
          mount-point: "{{{ module_nfs_client.mount.path }}}"
          type: "nfs"
          options: "{{{ module_nfs_client.mount.opts }}}"
          skip-mount: ~
triggers:
    -
      name: "Reboot"
      command: "os:reboot"
